package summarizer

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	shared "go.crwd.dev/ce/zerotrust-analytics/domain"
)

func TestGenAIHubGeneratorSummarize(t *testing.T) {
	var gotReq genAIHubRequest

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if got, want := r.Header.Get("Authorization"), "Bearer test-key"; got != want {
			t.Fatalf("Authorization header = %q, want %q", got, want)
		}
		if err := json.NewDecoder(r.Body).Decode(&gotReq); err != nil {
			t.Fatalf("Decode returned error: %v", err)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"markdown":"## Executive Summary\n\nGenerated by GenAI Hub."}`))
	}))
	defer server.Close()

	generator := &GenAIHubGenerator{
		endpoint: server.URL,
		model:    "claude-test",
		apiKey:   "test-key",
		client:   server.Client(),
	}

	report := &shared.CIDReport{
		CID:                 "cid-123",
		NumAIDs:             17,
		AverageOverallScore: 87.4,
		AverageOSScore:      84.2,
	}

	got, err := generator.Summarize(context.Background(), report)
	if err != nil {
		t.Fatalf("Summarize returned error: %v", err)
	}
	if !strings.Contains(got, "Generated by GenAI Hub.") {
		t.Fatalf("Summarize() = %q, want generated markdown", got)
	}
	if gotReq.Model != "claude-test" {
		t.Fatalf("request model = %q, want %q", gotReq.Model, "claude-test")
	}
	if !strings.Contains(gotReq.Prompt, report.CID) {
		t.Fatalf("request prompt did not contain report CID %q", report.CID)
	}
}
