package summarizer

import (
	"context"
	"errors"
	"strings"
	"testing"

	shared "go.crwd.dev/ce/zerotrust-analytics/domain"
)

func TestGenAIHubGeneratorSummarize(t *testing.T) {
	invoker := &fakeTextInvoker{
		markdown: "## Executive Summary\n\nGenerated by GenAI Hub.",
	}
	generator, err := newGenAIHubGenerator("claude-test", invoker)
	if err != nil {
		t.Fatalf("newGenAIHubGenerator returned error: %v", err)
	}

	report := &shared.CIDReport{
		CID:                 "cid-123",
		NumAIDs:             17,
		AverageOverallScore: 87.4,
		AverageOSScore:      84.2,
	}

	got, err := generator.Summarize(context.Background(), report)
	if err != nil {
		t.Fatalf("Summarize returned error: %v", err)
	}
	if !strings.Contains(got, "Generated by GenAI Hub.") {
		t.Fatalf("Summarize() = %q, want generated markdown", got)
	}
	if !strings.Contains(invoker.prompt, report.CID) {
		t.Fatalf("request prompt did not contain report CID %q", report.CID)
	}
}

func TestGenAIHubGeneratorSummarizeReturnsInvokerError(t *testing.T) {
	wantErr := errors.New("model unavailable")
	generator, err := newGenAIHubGenerator("claude-test", &fakeTextInvoker{err: wantErr})
	if err != nil {
		t.Fatalf("newGenAIHubGenerator returned error: %v", err)
	}

	_, err = generator.Summarize(context.Background(), &shared.CIDReport{CID: "cid-123"})
	if err == nil {
		t.Fatal("expected Summarize to return an error")
	}
	if !strings.Contains(err.Error(), "invoke model claude-test") {
		t.Fatalf("error = %q, want model context", err.Error())
	}
}

func TestGenAIHubGeneratorSummarizeRejectsEmptyMarkdown(t *testing.T) {
	generator, err := newGenAIHubGenerator("claude-test", &fakeTextInvoker{markdown: "   "})
	if err != nil {
		t.Fatalf("newGenAIHubGenerator returned error: %v", err)
	}

	_, err = generator.Summarize(context.Background(), &shared.CIDReport{CID: "cid-123"})
	if err == nil {
		t.Fatal("expected Summarize to reject empty markdown")
	}
}

type fakeTextInvoker struct {
	prompt   string
	markdown string
	err      error
}

func (f *fakeTextInvoker) InvokeWithText(_ context.Context, prompt string) (string, error) {
	f.prompt = prompt
	return f.markdown, f.err
}
