package summarizer

import (
	"fmt"
	"strings"

	shared "go.crwd.dev/ce/zerotrust-analytics/domain"
)

const (
	summaryPrefix       = "summary/cids/"
	summaryObjectSuffix = ".md"
)

// RenderPlaceholderSummary returns a deterministic Markdown summary for a CID
// report. This is the pre-LLM placeholder used to exercise the write path.
func RenderPlaceholderSummary(report *shared.CIDReport) string {
	var b strings.Builder

	fmt.Fprintf(&b, "## Zero Trust Audit Narrative\n\n")
	fmt.Fprintf(&b, "### Executive Summary\n\n")
	fmt.Fprintf(
		&b,
		"CID `%s` covers %d aids across %d platforms. The current overall score is %.2f and the OS score is %.2f.\n\n",
		report.CID,
		report.NumAIDs,
		len(report.Platforms),
		report.AverageOverallScore,
		report.AverageOSScore,
	)
	fmt.Fprintf(&b, "### Platform Highlights\n\n")
	for _, platform := range report.Platforms {
		fmt.Fprintf(
			&b,
			"- %s: %d aids, overall %.2f, OS %.2f.\n",
			platform.Name,
			platform.NumAIDs,
			platform.AverageOverallScore,
			platform.AverageOSScore,
		)
	}
	fmt.Fprintf(&b, "\n### Demo Note\n\n")
	fmt.Fprintf(&b, "This placeholder summary was generated by the summarizer write path for CID `%s`.\n", report.CID)

	return b.String()
}

func summaryObjectKey(cid string) string {
	return summaryPrefix + cid + summaryObjectSuffix
}
